Architecture-separated build for macOS
Signed-off-by: Kaito Udagawa <umireon@kaito.tokyo>

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -8,109 +8,187 @@ set -euo pipefail
 shopt -s nullglob
 
 debian_forky() {
-  cmake -B "${PLUGIN_BUILD_DIR:-.}/build" --preset linux
-  cmake --build "${PLUGIN_BUILD_DIR:-.}/build" --preset linux
-  (cd "${PLUGIN_BUILD_DIR:-.}/build" && cpack -G DEB)
+  cmake -B "${PLUGIN_BUILD_DIR:-${PWD:?}}/build" --preset linux
+  cmake --build "${PLUGIN_BUILD_DIR:-${PWD:?}}/build" --preset linux
+  (cd "${PLUGIN_BUILD_DIR:-${PWD:?}}/build" && cpack -G DEB)
 }
 
 ubuntu_resolute() {
-  cmake -G Ninja -S "$ROOT_DIR" -B "${PLUGIN_BUILD_DIR:-.}/build"
+  cmake -G Ninja -S "$ROOT_DIR" -B "${PLUGIN_BUILD_DIR:-${PWD:?}}/build"
 
-  cmake --build "${PLUGIN_BUILD_DIR:-.}/build"
+  cmake --build "${PLUGIN_BUILD_DIR:-${PWD:?}}/build"
 
-  (cd "${PLUGIN_BUILD_DIR:-.}/build" && cpack -G DEB)
+  (cd "${PLUGIN_BUILD_DIR:-${PWD:?}}/build" && cpack -G DEB)
 
-  . "${PLUGIN_BUILD_DIR:-.}/build/cmake_export.sh"
+  . "${PLUGIN_BUILD_DIR:-${PWD:?}}/build/cmake_export.sh"
 
   printf 'Run the following command to install the plugin:\n'
   printf '  sudo dpkg -i %s\n' "$ROOT_DIR/release/${PLUGIN_NAME}_*.deb"
 }
 
 arch() {
-  cmake -G Ninja -S "$ROOT_DIR" -B "${PLUGIN_BUILD_DIR:-.}/build_plugin"
+  cmake -G Ninja -S "$ROOT_DIR" -B "${PLUGIN_BUILD_DIR:-${PWD:?}}/build_plugin"
 
-  cmake --build "${PLUGIN_BUILD_DIR:-.}/build_plugin"
+  cmake --build "${PLUGIN_BUILD_DIR:-${PWD:?}}/build_plugin"
 
   printf 'Run the following command to install the plugin:\n'
-  printf '  sudo cmake --install %q --prefix /usr\n' "${PLUGIN_BUILD_DIR:-.}/build_plugin"
+  printf '  sudo cmake --install %q --prefix /usr\n' "${PLUGIN_BUILD_DIR:-${PWD:?}}/build_plugin"
 }
 
 macos() {
-  : "${PLUGIN_BUILD_DIR:=$PWD}"
-  : "${VCPKG_ROOT:=${PLUGIN_BUILD_DIR:-.}/vcpkg}"
+  : "${PLUGIN_BUILD_DIR:=${PWD:?}}"
+  export PLUGIN_BUILD_DIR
 
-  xcbeautify() { if command -v xcbeautify >/dev/null 2>&1; then command xcbeautify; else cat; fi; }
+  : "${CMAKE_OSX_DEPLOYMENT_TARGET:=12.0}"
+  : "${VCPKG_BINARY_SOURCES:=clear;files,${PLUGIN_BUILD_DIR:?}/.vcpkg_archives,readwrite}"
+  : "${VCPKG_ROOT:=${PLUGIN_BUILD_DIR:?}/vcpkg}"
+  export CMAKE_OSX_DEPLOYMENT_TARGET VCPKG_BINARY_SOURCES VCPKG_ROOT
 
-  if [[ -z "${VCPKG_BINARY_SOURCES:-}" ]]; then
-    VCPKG_BINARY_SOURCES="clear;files,${PLUGIN_BUILD_DIR:-.}/.vcpkg_archives,readwrite;http,https://vcpkg-obs.kaito.tokyo/{sha},read"
+  if [[ "${X86_64+set}" != 'set' ]] && [[ "$(uname -m)" == 'x86_64' ]]; then
+    X86_64=1
+  fi
+  export X86_64
+
+  if [[ "${X86_64:-0}" == '0' ]]; then
+    : "${CMAKE_OSX_ARCHITECTURES:=arm64}"
+    : "${VCPKG_TARGET_TRIPLET:=arm64-osx-obs}"
+    : "${VCPKG_ORT_TARGET_TRIPLET:=arm64-osx-obs-ort}"
+  else
+    : "${CMAKE_OSX_ARCHITECTURES:=x86_64}"
+    : "${VCPKG_TARGET_TRIPLET:=x64-osx-obs}"
+    : "${VCPKG_ORT_TARGET_TRIPLET:=x64-osx-obs-ort}"
+  fi
+  export CMAKE_OSX_ARCHITECTURES VCPKG_TARGET_TRIPLET VCPKG_ORT_TARGET_TRIPLET
+
+  local obs_studio_git_tag onnxruntime_git_tag onnxruntime_reduced_ops_config
+  eval "$(awk '/^(obs_studio|onnxruntime)_git_tag=|^onnxruntime_reduced_ops_config=/ { print }' buildspec.props)"
+
+  local prebuilt_macos_name qt6_macos_name
+  eval "$(awk '/^(prebuilt|qt6)_macos_name=/ { print }' buildspec.props)"
+  printf 'INFO: buildspec.props loaded\n' >&2
+
+  CMAKE_COMMAND="$(PATH=/usr/bin:/bin "${VCPKG_ROOT:?}/vcpkg" fetch cmake | tail -n1)"
+  export CMAKE_COMMAND
+  printf "INFO: cmake found at %s\n" "${CMAKE_COMMAND:?}" >&2
+
+  NINJA_COMMAND="$(PATH=/usr/bin:/bin "${VCPKG_ROOT:?}/vcpkg" fetch ninja | tail -n1)"
+  export NINJA_COMMAND
+  printf "INFO: ninja found at %s\n" "${NINJA_COMMAND:?}" >&2
+
+  PKG_CONFIG_BINDIR="$(brew --prefix pkg-config)/bin"
+  export PKG_CONFIG_BINDIR
+  printf "INFO: pkg-config found at %s\n" "${PKG_CONFIG_BINDIR:?}" >&2
+
+  export PATH="${CMAKE_COMMAND%/*}:${NINJA_COMMAND%/*}:${PKG_CONFIG_BINDIR:?}:/usr/bin:/bin"
+  printf 'INFO: PATH set to %s\n' "$PATH" >&2
+
+  "${VCPKG_ROOT:?}/vcpkg" install --triplet="${VCPKG_TARGET_TRIPLET:-arm64-osx-obs}" --x-install-root="${PLUGIN_BUILD_DIR:-${PWD:?}}/vcpkg_installed"
+  printf "INFO: vcpkg dependencies were installed at %q\n" "${PLUGIN_BUILD_DIR:-${PWD:?}}/vcpkg_installed" >&2
+
+  cmake \
+    -S "${PLUGIN_BUILD_DIR:-${PWD:?}}/obs-studio" \
+    -B "${PLUGIN_BUILD_DIR:-${PWD:?}}/build_obs" \
+    -G "Xcode" \
+    -DCMAKE_INSTALL_PREFIX="${PLUGIN_BUILD_DIR:-${PWD:?}}/obs_installed" \
+    -DCMAKE_OSX_ARCHITECTURES="${CMAKE_OSX_ARCHITECTURES:?}" \
+    -DCMAKE_OSX_DEPLOYMENT_TARGET="${CMAKE_OSX_DEPLOYMENT_TARGET:?}" \
+    -DCMAKE_PREFIX_PATH="$(deps=("${PLUGIN_BUILD_DIR:-${PWD:?}}"/macos-deps-*); IFS=';'; printf '%s' "${deps[*]}")" \
+    -DENABLE_FRONTEND=OFF \
+    -DENABLE_PLUGINS=OFF \
+    -DOBS_CMAKE_VERSION=3.0.0 \
+    -DOBS_VERSION_OVERRIDE="${obs_studio_git_tag:-32.0.0}"
+  printf "INFO: obs-studio was configured\n" >&2
+
+  cmake --build "${PLUGIN_BUILD_DIR:-${PWD:?}}/build_obs" --target obs-frontend-api --config Release --parallel
+  printf "INFO: obs-studio was built\n" >&2
+
+  cmake --install "${PLUGIN_BUILD_DIR:-${PWD:?}}/build_obs" --component Development --config Release --prefix "${PLUGIN_BUILD_DIR:-${PWD:?}}/obs_installed"
+  printf "INFO: obs-studio was installed\n" >&2
+
+  "${VCPKG_ROOT:?}/vcpkg" install \
+    --triplet="${VCPKG_ORT_TARGET_TRIPLET:-arm64}" \
+    --overlay-triplets="${PWD:?}/vcpkg-triplets" \
+    --x-feature=coreml-ep \
+    --x-install-root="${PLUGIN_BUILD_DIR:-${PWD:?}}/vcpkg_ort_installed" \
+    --x-manifest-root="${PLUGIN_BUILD_DIR:-${PWD:?}}/onnxruntime/cmake"
+  printf "INFO: vcpkg dependencies of onnxruntime were installed\n" >&2
+
+  if [[ -n "${onnxruntime_reduced_ops_config:-}" ]] && [[ -f "${PWD:?}/${onnxruntime_reduced_ops_config:?}" ]]; then
+    "${PLUGIN_BUILD_DIR:-${PWD:?}}/.venv/bin/python3" \
+      "${PLUGIN_BUILD_DIR:-${PWD:?}}/onnxruntime/tools/ci_build/reduce_op_kernels.py" \
+      "${PWD:?}/${onnxruntime_reduced_ops_config:?}" \
+      --cmake_build_dir "${PLUGIN_BUILD_DIR:-${PWD:?}}/build_ort" \
+      --is_extended_minimal_build_or_higher
+    export onnxruntime_REDUCED_OPS_BUILD=ON
+    printf "INFO: reduced ONNX Runtime operators were generated\n" >&2
   fi
 
-  export PLUGIN_BUILD_DIR VCPKG_ROOT VCPKG_BINARY_SOURCES
-
-  local pwshExe cmakeExe ninjaExe
-  pwshExe=$("${VCPKG_ROOT:?}/vcpkg" fetch powershell-core | tail -n1)
-  cmakeExe=$("${VCPKG_ROOT:?}/vcpkg" fetch cmake | tail -n1)
-  ninjaExe=$("${VCPKG_ROOT:?}/vcpkg" fetch cmake | tail -n1)
-
-  if ! [[ -e "$cmakeExe" ]]; then
-    printf 'ERROR: cmake not found.\n'; exit 1
+  if [[ "${PLUGIN_BUILD_DIR:?}" == "${PWD:?}" ]]; then
+    export CCACHE_BASEDIR="${PLUGIN_BUILD_DIR:?}"
   fi
 
-  if ! [[ -e "$pwshExe" ]]; then
-    printf 'ERROR: pwsh not found.\n'; exit 1
-  fi
-
-  PATH="${pwshExe%/*}:${cmakeExe%/*}:${ninjaExe%/*}:$PATH"
-  export PATH
-
-  printf '#==> Install vcpkg dependencies\n'
-
-  "${VCPKG_ROOT:?}/vcpkg" install --triplet=arm64-osx-obs --x-install-root="${PLUGIN_BUILD_DIR:-.}/vcpkg_arm64_installed"
-  "${VCPKG_ROOT:?}/vcpkg" install --triplet=x64-osx-obs --x-install-root="${PLUGIN_BUILD_DIR:-.}/vcpkg_x64_installed"
-
-  ./scripts/lipo_vcpkg_macos.sh \
-    "${PLUGIN_BUILD_DIR:-.}/vcpkg_installed/universal-osx-obs" \
-    "${PLUGIN_BUILD_DIR:-.}/vcpkg_arm64_installed/arm64-osx-obs" \
-    "${PLUGIN_BUILD_DIR:-.}/vcpkg_x64_installed/x64-osx-obs"
-
-  printf '#==> Build OBS sources\n'
-
-  pwsh -NoProfile -Command "Import-Module ./scripts/BuildOBS.psm1 && Invoke-ObsConfigure"
-  pwsh -NoProfile -Command "Import-Module ./scripts/BuildOBS.psm1 && Invoke-ObsBuild"
-  pwsh -NoProfile -Command "Import-Module ./scripts/BuildOBS.psm1 && Install-Obs"
-
-  printf '#==> Build ONNX Runtime\n'
-
-  export CCACHE_DIR="${PLUGIN_BUILD_DIR:-.}/.ccache_ort"
+  export CCACHE_DIR="${PLUGIN_BUILD_DIR:-${PWD:?}}/.ccache_ort"
   export CCACHE_SLOPPINESS='include_file_mtime,time_macros'
 
-  if [[ "${PLUGIN_BUILD_DIR:-.}" == "$PWD" ]]; then
-    export CCACHE_BASEDIR="${PLUGIN_BUILD_DIR:-.}"
+  cmake \
+    -S "${PLUGIN_BUILD_DIR:-${PWD:?}}/onnxruntime/cmake" \
+    -B "${PLUGIN_BUILD_DIR:-${PWD:?}}/build_ort" \
+    -G Ninja \
+    --compile-no-warning-as-error \
+    -DCMAKE_BUILD_TYPE=Release \
+    -DCMAKE_C_COMPILER_LAUNCHER="${PLUGIN_BUILD_DIR:-${PWD:?}}/.bin/ccache" \
+    -DCMAKE_CXX_COMPILER_LAUNCHER="${PLUGIN_BUILD_DIR:-${PWD:?}}/.bin/ccache" \
+    -DCMAKE_OSX_ARCHITECTURES="${CMAKE_OSX_ARCHITECTURES:?}" \
+    -DCMAKE_OSX_DEPLOYMENT_TARGET="${CMAKE_OSX_DEPLOYMENT_TARGET:?}" \
+    -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
+    -DCMAKE_TOOLCHAIN_FILE="${VCPKG_ROOT:?}/scripts/buildsystems/vcpkg.cmake" \
+    -Donnxruntime_BUILD_SHARED_LIB=OFF \
+    -Donnxruntime_BUILD_UNIT_TESTS=OFF \
+    -Donnxruntime_DISABLE_RTTI=OFF \
+    -Donnxruntime_REDUCED_OPS_BUILD="${onnxruntime_REDUCED_OPS_BUILD:-OFF}" \
+    -Donnxruntime_RUN_ONNX_TESTS=OFF \
+    -Donnxruntime_USE_COREML=ON \
+    -Donnxruntime_USE_VCPKG=ON \
+    -DPython_EXECUTABLE="${PLUGIN_BUILD_DIR:-${PWD:?}}/.venv/bin/python3" \
+    -DVCPKG_INSTALLED_DIR="${PLUGIN_BUILD_DIR:-${PWD:?}}/vcpkg_ort_installed" \
+    -DVCPKG_MANIFEST_INSTALL=OFF \
+    -DVCPKG_OVERLAY_TRIPLETS="${PWD:?}/vcpkg-triplets" \
+    -DVCPKG_TARGET_TRIPLET="${VCPKG_ORT_TARGET_TRIPLET:-arm64-macos-obs-ort}"
+  printf "INFO: onnxruntime was configured\n" >&2
+
+  cmake --build "${PLUGIN_BUILD_DIR:-${PWD:?}}/build_ort" --config Release --parallel
+  printf "INFO: onnxruntime was built\n" >&2
+
+  cmake --install "${PLUGIN_BUILD_DIR:-${PWD:?}}/build_ort" --prefix "${PLUGIN_BUILD_DIR:-${PWD:?}}/ort_installed"
+  printf "INFO: onnxruntime was installed\n" >&2
+
+  unset CCACHE_BASEDIR CCACHE_DIR CCACHE_SLOPPINESS
+
+  cmake \
+    -S "${PWD:?}" \
+    -B "${PLUGIN_BUILD_DIR:-${PWD:?}}/build" \
+    -G Ninja \
+    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
+    -DCMAKE_OSX_ARCHITECTURES="${CMAKE_OSX_ARCHITECTURES:?}" \
+    -DCMAKE_OSX_DEPLOYMENT_TARGET="${CMAKE_OSX_DEPLOYMENT_TARGET:?}" \
+    -DCMAKE_PREFIX_PATH="$(deps=("${PLUGIN_BUILD_DIR:-${PWD:?}}"/macos-deps-*); IFS=';'; printf '%s' "${deps[*]}");${PLUGIN_BUILD_DIR:-${PWD:?}}/obs_installed;${PLUGIN_BUILD_DIR:-${PWD:?}}/obs_installed/Frameworks;${PLUGIN_BUILD_DIR:-${PWD:?}}/vcpkg_ort_installed/${VCPKG_ORT_TARGET_TRIPLET:-arm64-osx-obs-ort};${PLUGIN_BUILD_DIR:-${PWD:?}}/ort_installed;${PLUGIN_BUILD_DIR:-${PWD:?}}/vcpkg_installed/${VCPKG_TARGET_TRIPLET:-arm64-osx-obs}"
+  printf "INFO: plugin was configured\n" >&2
+
+  cmake --build "${PLUGIN_BUILD_DIR:-${PWD:?}}/build" --config RelWithDebInfo --parallel
+  printf "INFO: plugin was built\n" >&2
+
+  cmake --install "${PLUGIN_BUILD_DIR:-${PWD:?}}/build" --config RelWithDebInfo --prefix "${PLUGIN_BUILD_DIR:-${PWD:?}}/build_prefix"
+
+  local plugin_bundle_path="${PLUGIN_BUILD_DIR:-${PWD:?}}/build_prefix/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin"
+  if ! [[ -d "${plugin_bundle_path:?}" ]]; then
+    printf "ERROR: plugin bundle was not found\n" >&2
+    exit 1
   fi
 
-  pwsh -NoProfile -Command "Import-Module ./scripts/BuildOnnxRuntime.psm1 && Invoke-OrtBuildPy -Command update -Arch arm64"
-  pwsh -NoProfile -Command "Import-Module ./scripts/BuildOnnxRuntime.psm1 && Invoke-OrtBuildPy -Command build -Arch arm64"
-  pwsh -NoProfile -Command "Import-Module ./scripts/BuildOnnxRuntime.psm1 && Invoke-OrtBuildPy -Command update -Arch x86_64"
-  pwsh -NoProfile -Command "Import-Module ./scripts/BuildOnnxRuntime.psm1 && Invoke-OrtBuildPy -Command build -Arch x86_64"
+  codesign -f -s - -o runtime "${plugin_bundle_path:?}"
 
-  unset CCACHE_DIR CCACHE_SLOPPINESS CCACHE_BASEDIR
-
-  pwsh -NoProfile -Command "Import-Module ./scripts/BuildOnnxRuntime.psm1 && Install-Ort"
-
-  ./scripts/lipo_vcpkg_macos.sh \
-    "${PLUGIN_BUILD_DIR:-.}/vcpkg_ort_installed/universal-osx" \
-    "${PLUGIN_BUILD_DIR:-.}/build_ort_arm64/Release/vcpkg_installed/arm64-osx" \
-    "${PLUGIN_BUILD_DIR:-.}/build_ort_x86_64/Release/vcpkg_installed/x64-osx"
-
-  printf '#==> Build Plugin\n'
-
-  cmake --preset macos --config "$PLUGIN_CONFIG"
-  cmake --build --preset macos --config "$PLUGIN_CONFIG" | xcbeautify
-
-  . "${PLUGIN_BUILD_DIR:-.}/build/cmake_export.sh"
-
-  printf 'Run the following command to install the plugin:\n'
-  printf '  cmake --install "%s" --config "%s" --prefix ~\n' "${PLUGIN_BUILD_DIR:-.}/build" "$PLUGIN_CONFIG"
+  printf 'INFO: Run the following command to install the plugin into OBS Studio:\n' >&2
+  printf "INFO: ditto --norsrc %q %q\n" "${plugin_bundle_path:?}" "$HOME/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin" >&2
 }
 
 if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
